### ISSUE TITLE
[HELP] Simple To Do --> hashowanie hasła i wysyłanie maili  

### ISSUE THREAD

**Issue by MacBry** [1024kb-pl/StowarzyszenieNaukiJavy#17]
# Simple ToDo App
Hej wszystkim
Czyli jeśli dobrze rozumiem to w bazie danych mamy trzymać hasło już w formie hasha i przy logowaniu mamy hashować podane dane od użytkownika i wynik porównywać z tym co jest w bazie ?

Druga sprawa tyczy się resetowania  hasła poprzez maila. Czy możecie polecić jakiś prosty tutek gdzie jest to opisane. Przykłady z javax.mail przy próbie wysłania wiadomości z poczty wp.pl powodują dziwne błędy i odmowy. Może jest jakaś alternatywa do tego API

Pozdrawiam :)

# Inne informacje

**Comment by 1024kb-pl** [comment]
Hej,
co do pierwszego pytania - to odpowiedź brzmi tak. Nie powinno się trzymać haseł plain textem w bazie danych, powinny być hashowane. Właśnie jednym ze sposobu jest użycie MD5.

Próbowałeś wysyłać emaila w ten sposób? https://www.journaldev.com/2532/javamail-example-send-mail-in-java-smtp
Jeśli tak po pokaż te dziwne błędy, może problem leży gdzieś po stronie konfiguracji - np. zamknięte porty.

**Comment by MacBry** [comment]
Na podstawie podanego linku to są moje dwie klasy do wysyłania maili
https://pastebin.com/Aks4DvmU
https://pastebin.com/tXW7BgYp

Po uruchomieniu dostaje:
https://pastebin.com/0aECkGAi

Może źle ustawiam jakieś właściwości :/ Jak co czekam na sugestie :)

**Comment by 1024kb-pl** [comment]
Skupiaj się zawsze na czytaniu błędów i wklejaniu ich odpowiednich części w google z dopiskiem 'stackoverflow'. Już tłumaczę o co chodzi.

Twoje logi mówią, że:
```
javax.mail.MessagingException: Could not connect to SMTP host: localhost, port: 25;
```
Czyli javax.mail nie może się połączyć z SMTP serwerem pod adresem: localhost:25 - czyli nie masz serwera SMTP w swojej sieci na porcie 25.

Przechodząc przez kod widzę, że chcesz korzystaćz wp jako serwera SMTP - w takim razie problem wynika z konfiguracji. Spójrz na poniższą linię kodu:
```
        props.put("smtp.wp.pl", smtpHostServer);
```
A na tą:
```
	    props.put("mail.smtp.host", smtpHostServer);
```
Obiekt properties jest jak mapa - metoda put jako pierwszy argument przyjmuje klucz, który się nie zmienia w żadnym przypadku - konfiguruejsz host to używasz **mail.smtp.host**, a dopiero w drugi argument wrzucasz wartość tego klucza - czyli Ty u siebie: **smtp.wp.pl**

Jak coś nadal nie będzie działać to sprawdź porty - może być, że smtp.wp.pl jest wystawiony na innym niż 25, tak jak to javax.mail domyślnie szuka.

**Comment by MacBry** [comment]
Dzięki wielkie Wysyłanie działa!
